image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar artifacts/app-ibank-build-for-testers.jar -port=7777 &
  - chmod +x gradlew

build_script:
  - chmod +x gradlew
  - ./gradlew test --info
  - ./gradlew test -Dselenide.headless=true --info